# Site settings
title: "CS and Maths Tutorials: Bringing it Together"
email: "N.Lawrence@sheffield.ac.uk"
description: > # this means to ignore newlines until "baseurl:"
  Tutorials for students at the interface of Computer Science and Mathematics: Bringing it Together Focuses on themes that unite our domains.
baseurl: "/tutorials" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  sods

# Build settings
markdown: kramdown
